const Colors = {
    TRANSPARENT: 'transparent',
    PRIMARY_COLOR: '#0E2C39',
    ACCENT_COLOR: '#39CFBA',
    ACCENT_REVERSE: '#FCE9AD',
    WHITE_COLOR: '#FFFFFF',
    BLACK_COLOR: '#000000',
    Fancy: {
        COLOR_GREEN: '#159782',
        COLOR_YELLOW: '#FBC02E',
        COLOR_RED: '#BA0000',
        COLOR_PURPLE: '#AD00AD',
        COLOR_ORANGE: '#FD9976'
    },
    Button: {
        PRIMARY_COLOR: '#39CFBA',
        YELLOW_COLOR: '#FBC02E'
    },
    TextInput: {
        TINT_COLOR_GREEN: '#B9F8EC'
    },
    Slot: {
        AVAILABLE: '#39CFBA',
        NOT_AVAILABLE: '#707070',
        ON_GOING: '#FD9976',
        MY_SLOT: '#0E2C39'
    },
    Shades: {
        COLOR_GREEN: '#B9F8EC',
        COLOR_BLUE: '#E0FAFF',
        COLOR_INACTIVE: '#C1C1C1',
        COLOR_PLACEHOLDER: '#707070',
        COLOR_BLACK: '#000000',
        COLOR_MINE_SHAFT: '#333333',
        COLOR_DOVE_GRAY: '#666666',
        COLOR_DUSTY_GRAY: '#999999',
        COLOR_SILVER: '#CCCCCC',
        COLOR_MERCURY: '#E6E6E6',
        COLOR_CONCRETE: '#F3F3F3',
        COLOR_ERROR: '#B00020'
    },
    SCREEN_BACKGROUND_COLOR: '#FFFFFF',
    GREEN_BACKGROUND_COLOR: '#EBFFFB',
    YELLOW_BACKGROUND_COLOR: '#FEF9E9',
    INACTIVE_BACKGROUND_COLOR: '#FAFAFA',
    SILVER_BACKGROUND_COLOR: '#F5F5F5',
    Text: {
        PRIMARY_COLOR: '#0E2C39',
        SECONDARY_COLOR: '#39CFBA',
        ERROR_COLOR: '#B00020',
        LINK_COLOR: '#2699FB',
        WHITE_COLOR: '#FFFFFF',
        INACTIVE_COLOR: '#C1C1C1',
        SUB_DETAIL_COLOR: '#6E8087'
    },
    NOTIFICATION_BOX_COLOR: '#F5F5F5',
    NOTIFICATION_BACKGROUND: '#FEF9E9',
    NOTIFICATION_BG_UNREAD: '#F1F9FF',
    BG_FAMILY_MEMBER_IMAGE: '#6E8087'
};
export { Colors };